name: Mirror to Account B
on:
  push:
    branches:
      - main  
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if token exists
        run: |
          if [ -z "$ACCOUNT_B_TOKEN" ]; then
            echo "Token is empty"
            exit 1
          else
            echo "Token is set, length: ${#ACCOUNT_B_TOKEN}"
          fi
        env:
          ACCOUNT_B_TOKEN: ${{ secrets.ACCOUNT_B_TOKEN }}
          
  
