name: Mirror to Account B
on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug - Check Token Presence
        run: |
          if [ -z "$ACCOUNT_B_TOKEN" ]; then
            echo "Token is empty"
            exit 1
          else
            echo "Token is set. Length: ${#ACCOUNT_B_TOKEN}"
          fi
        env:
          ACCOUNT_B_TOKEN: ${{ secrets.ACCOUNT_B_TOKEN }}

      - name: Debug - Test Repository Access
        run: |
          echo "Testing repository access with curl..."
          # This command will check if the repository is accessible with the provided token.
          curl -u "nahid-e:${ACCOUNT_B_TOKEN}" https://api.github.com/repos/nahid-e/e-commerce
        env:
          ACCOUNT_B_TOKEN: ${{ secrets.ACCOUNT_B_TOKEN }}

      - name: Mirror Repository
        env:
          ACCOUNT_B_TOKEN: ${{ secrets.ACCOUNT_B_TOKEN }}
        run: |
          REMOTE_URL="https://nahid-e:${ACCOUNT_B_TOKEN}@github.com/nahid-e/e-commerce.git"
          echo "Using remote URL: $REMOTE_URL"
          git remote add mirror "$REMOTE_URL"
          git push mirror --mirror
