name: Mirror to Account B
on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug - Check Token Presence
        run: |
          if [ -z "$ACCOUNT_B_TOKEN" ]; then
            echo "Token is empty"
            exit 1
          else
            echo "Token is set. Length: ${#ACCOUNT_B_TOKEN}"
          fi
        env:
          ACCOUNT_B_TOKEN: ${{ secrets.ACCOUNT_B_TOKEN }}

      - name: Debug - Prepare Remote URL
        run: |
          # Construct the remote URL using an environment variable.
          # This avoids issues with special characters.
          REMOTE_URL="https://nahid-e:${ACCOUNT_B_TOKEN}@github.com/nahid-e/e-commerce.git"
          echo "Remote URL: $REMOTE_URL"
        env:
          ACCOUNT_B_TOKEN: ${{ secrets.ACCOUNT_B_TOKEN }}

      - name: Mirror Repository
        env:
          ACCOUNT_B_TOKEN: ${{ secrets.ACCOUNT_B_TOKEN }}
        run: |
          # Construct the remote URL and add it as the remote named "mirror"
          REMOTE_URL="https://nahid-e:${ACCOUNT_B_TOKEN}@github.com/nahid-e/e-commerce.git"
          echo "Using remote URL: $REMOTE_URL"
          git remote add mirror "$REMOTE_URL"
          git push mirror --mirror
